title: "jekyll-shell-theme"
description: "This is a preview of jekyll-shell-theme."
github_username: tareqdandachi

theme: jekyll-shell-theme

plugins:
  - jemoji

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - about.md
  - theme_preview.md
  - read_me.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
