title: "Shell Theme"
description: "This is a description of my awesome hacker site."
github_username: tareqdandachi

theme: jekyll-shell-theme

plugins:
  - jemoji

sass:
  style: compressed

header_pages:
  - index.md
  - about.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
