title: "0x1337"
tagline: "The IIITH Hacking Club"
description: "Exploiting vulnerabilities for fun and teaching about security in today's world"
github_username: notrudyyy
baseurl: ""
url: "https://tareqdandachi.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - members.md
  - events.md
  - writeups.md

# set the size of the text to 'large' or 'small', default is small
font-size: small