# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: "0x1337"
email: hacking.club@students.iiit.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  We are a club based on ethical hacking, where we try to familiarize people with different tools and ways of ethical hacking and make them aware about how cybersecurity is so important in today’s world.
baseurl: "/" # the subpath of your site
url: "domain.xyz" # the base hostname & protocol for your site
github_username:  notrudyyy

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  - a-third-page.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]
